CREATE TABLE IF NOT EXISTS compilation
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT compilation_pk
            PRIMARY KEY,
    title  VARCHAR,
    pinned BOOLEAN
);

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT users_pk
            PRIMARY KEY,
    name  VARCHAR,
    email VARCHAR UNIQUE
);

CREATE TABLE IF NOT EXISTS category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT category_pk
            PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS event
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT event_pk
            PRIMARY KEY,
    annotation         VARCHAR,
    category_id        BIGINT
        CONSTRAINT event_category_id_fk
            REFERENCES category,
    confirmed_requests INTEGER,
    created_on         TIMESTAMP,
    description        VARCHAR,
    state_action       VARCHAR,
    event_date         TIMESTAMP,
    initiator_id       BIGINT
        CONSTRAINT event_users_id_fk
            REFERENCES users,
    paid               BOOLEAN,
    participant_limit  BIGINT,
    published_on       TIMESTAMP,
    request_moderation BOOLEAN,
    state              VARCHAR,
    title              VARCHAR,
    views              BIGINT,
    lat                REAL,
    lon                REAL,
    compilation_id     BIGINT
        CONSTRAINT event_compilation_id_fk
            REFERENCES compilation
);

CREATE TABLE IF NOT EXISTS event_participation_request
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT event_participation_request_pk
            PRIMARY KEY,
    event_id     BIGINT
        CONSTRAINT event_participation_request_event_id_fk
            REFERENCES event,
    created      TIMESTAMP,
    requester_id BIGINT
        CONSTRAINT event_participation_request_users_id_fk
            REFERENCES users,
    status       VARCHAR
);