version: '3.1'
services:
  stats-server:
    build: ./stats/stats-server
    container_name: stats_server_container
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats

  stats-db:
    image: postgres:13.7-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  ewm-service:
    build: ./ewm-service/.
    container_name: ewm_service_container
    depends_on:
      - stats-server
    ports:
      - "8080:8080"

  #  ewm-db:
  #   image: postgres:14-alpine

