create table if not exists stats
(
    id        bigint generated by default as identity
        constraint stats_pk
            primary key,
    app       varchar,
    uri       varchar,
    ip        varchar,
    timestamp timestamp
);